# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Dev server settings
[dev]
  framework = "vite"
  command = "npm run dev:vite"
  targetPort = 3000
  port = 8888
  autoLaunch = false
  publish = "dist"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production context
[context.production]
  command = "npm run build"

# Development context
[context.development]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Headers - Security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://app.sumit.co.il https://www.googletagmanager.com https://www.google-analytics.com https://maps.googleapis.com;
      connect-src 'self' https://api.sumit.co.il https://www.google-analytics.com https://maps.googleapis.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      frame-src 'self' https://app.sumit.co.il;
      media-src 'self' data: blob:;
    """

# Cache - Static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache - Image types (fixed!)
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache - Fonts
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Env vars
[build.environment]
  NODE_VERSION = "18"
  VITE_APP_NAME = "Spectra Salon"
  VITE_APP_VERSION = "1.0.0"
  # Allow public Vite envs and server keys; single consolidated list
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUMIT_API_KEY,VITE_SUMIT_ORGANIZATION_ID,VITE_SUMIT_API_URL,SUMIT_API_KEY,SUMIT_ORG_ID,SUMIT_ORGANIZATION_ID,SUMIT_API_URL"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,**/*.map"

# Netlify Functions config
[functions]
  external_node_modules = ["axios"]

[functions."summit-data-sync"]
  schedule = "0 2 * * *"
