# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5173

# Production context
[context.production]
  command = "npm run build"

# Development context
[context.development]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Additional environment variables for the app
[build.environment]
  NODE_VERSION = "18"
  VITE_APP_NAME = "Spectra Salon"
  VITE_APP_VERSION = "1.0.0" 