/**
 * src/lib/types/productTruth.ts
 * ─────────────────────────────────────────────────────────────────────────
 * Shared canonical domain contracts for the Product Truth system.
 *
 * These types mirror the static artifacts generated by
 * scripts/build-canonical-product-truth.js and the API shapes
 * returned by netlify/functions/product-truth-search.js.
 *
 * All admin screens (Product Truth, Product Catalog, Usage Imports,
 * Beauty Intelligence, Review Queue, AI Analyst) must use these types
 * instead of implementing their own matching or classification logic.
 */

// ── Product type taxonomy ──────────────────────────────────────────────────

export type ProductType =
  | "hair_color_shade"
  | "developer_oxidant"
  | "lightener_bleach"
  | "bond_builder"
  | "treatment_care"
  | "mixer_corrector"
  | "other";

// ── Validation statuses ────────────────────────────────────────────────────

export type ValidationStatus =
  | "approved"
  | "suggested_match"
  | "needs_review"
  | "unresolved"
  | "rejected_duplicate"
  | "inactive";

export type Confidence = "high" | "medium" | "low";

// ── Developer strength ─────────────────────────────────────────────────────

export interface DeveloperStrength {
  percent: number | null;
  volume: number | null;
  strengthKey: string;
}

// ── Canonical Product Identity ─────────────────────────────────────────────

export interface CanonicalProduct {
  canonicalId: string;
  brand: string;
  displayBrand: string;
  series: string;
  displaySeries: string;
  shade: string;
  displayShade: string;
  shadeDesc: string;
  familyShade: string;
  productType: ProductType;
  productTypeLabel: string;
  catalogType: string;
  productKind: string;
  developerStrength: DeveloperStrength | null;
  sizes: number[];
  primarySizeGrams: number | null;
  barcodes: string[];
  catalogNos: string[];
  image: string;
  hairColor: string;
  active: boolean;
  hasActiveRecords: number;
  hasBarcodes: boolean;
  validationStatus: ValidationStatus;
  confidence: Confidence;
  sourceCount: number;
  duplicatesMerged: number;
  aliasCount: number;
  reviewItemCount: number;
  excludeFromShadeIntelligence: boolean;
  isSupportingProduct: boolean;
}

// ── Product Alias ──────────────────────────────────────────────────────────

export type AliasType =
  | "shade_variant"
  | "shade_format"
  | "catalog_name"
  | "usage_report_name"
  | "brand_variation"
  | "product_line_variation"
  | "manual_alias"
  | "canonical_display"
  | "brand_shade_display"
  | "shade_only";

export interface ProductAlias {
  canonicalProductId: string;
  alias: string;
  normalizedAlias: string;
  aliasType: AliasType;
  source: string;
  confidence: Confidence;
  approvedBy?: string;
  approvedAt?: string;
  sourceRecordId?: string;
}

// ── Catalog Product Source ─────────────────────────────────────────────────

export interface CatalogProductSource {
  sourceId: string;
  canonicalProductId: string;
  canonicalKey: string;
  matchMethod: string;
  matchConfidence: Confidence;
  flag: 0 | 1 | 2 | 3; // 0=active 1=deleted 2=deprecated 3=barcode-conflict
  sourceBrandFile: string | null;
  originalPayload: {
    id: string;
    brand: string;
    series: string;
    familyShade: string;
    shade: string;
    type: string;
    rawType: string;
    productKind: string;
    materialWeight: number | null;
    packingWeight: number | null;
    barcodes: string[];
    barcode: string;
    barcodeCount: number;
    catalogNo: string;
    hairColor: string;
    image: string;
    flag: number;
    shadeDesc: string;
    price: number;
  };
}

// ── Product Review Item ────────────────────────────────────────────────────

export type ReviewSeverity = "critical" | "high" | "medium" | "low";

export interface ProductReviewItem {
  reason: string;
  severity: ReviewSeverity;
  canonicalProductId?: string;
  description: string;
  details?: Record<string, unknown>;
}

// ── Product Truth Funnel ───────────────────────────────────────────────────

export interface ProductTruthFunnel {
  generatedAt: string;
  totalCatalogRows: number;
  normalizedCatalogRows: number;
  exactDuplicatesMerged: number;
  aliasesMerged: number;
  canonicalProductsCreated: number;
  approvedCanonicalProducts: number;
  suggestedMatches: number;
  needsReview: number;
  inactive: number;
  unresolved: number;
  byProductType: Record<string, number>;
  byValidationStatus: Record<string, number>;
  topBrands: { brand: string; count: number }[];
  totalReviewItems: number;
  totalAliases: number;
  totalSources: number;
  buildDurationMs: number;
  appliedAdminChanges: number;
}

// ── Search Results ─────────────────────────────────────────────────────────

export interface ProductSearchResult {
  id: string;
  score?: number;
  brand?: string;
  series?: string;
  shade?: string;
  shadeDesc?: string;
  productType?: ProductType;
  productTypeLabel?: string;
  validationStatus?: ValidationStatus;
  confidence?: Confidence;
  active?: boolean;
  sourceCount?: number;
  aliasCount?: number;
  barcodes?: string[];
}

// ── Usage Import ───────────────────────────────────────────────────────────

export type ImportStatus =
  | "uploaded"
  | "parsing"
  | "resolving"
  | "needs_review"
  | "ready"
  | "reprocessing"
  | "failed";

export interface UsageResolutionSummary {
  reportId: string | null;
  totalUsageRows: number;
  uniqueRawProductNames: number;
  resolvedUsageRows: number;
  resolvedAuto: number;
  resolvedAlias: number;
  suggestedMatches: number;
  unresolvedUsageRows: number;
  resolutionRate: number;
  uniqueCanonicalProducts: number;
}

export interface UsageProductResolution {
  rawProductName: string;
  normalizedName: string;
  canonicalProductId: string | null;
  matchMethod: string;
  confidence: Confidence | "none";
  reviewStatus: "resolved" | "suggested_match" | "unresolved" | "empty";
  displayProduct?: {
    brand: string;
    series: string;
    shade: string;
    productType: ProductType;
    productTypeLabel: string;
    validationStatus: ValidationStatus;
    active: boolean;
  } | null;
}

// ── Admin domain navigation ────────────────────────────────────────────────

export type AdminDomain = "customer" | "data";

export type CustomerTab =
  | "cohorts"
  | "overview"
  | "success"
  | "billing";

export type DataTab =
  | "truth"
  | "products"
  | "beauty"
  | "imports"
  | "review"
  | "ai"
  | "operations";

export interface AdminNavState {
  domain: AdminDomain;
  customerTab: CustomerTab;
  dataTab: DataTab;
}

// ── AI operation types ─────────────────────────────────────────────────────

export type AIOperation =
  | "search_products"
  | "explain_match"
  | "find_duplicate_candidates"
  | "classify_product"
  | "summarize_conflict"
  | "analyze_usage"
  | "prioritize_review_queue";

export interface AIOperationParams {
  operation: AIOperation;
  productId?: string;
  candidateId?: string;
  query?: string;
  question?: string;
  reportId?: string;
}

export interface AIEvidence {
  type: string;
  referenceId: string;
  explanation: string;
}

export interface AIResult {
  answer: string;
  referencedProductIds: string[];
  confidence: number;
  evidence: AIEvidence[];
  suggestion: {
    type: string;
    targetProductId: string | null;
    reasoning: string;
  };
  domainCheck: {
    isDomainRequest: boolean;
    refusalReason: string | null;
  };
  securityFlags: unknown[];
}

// ── Pending changes (admin overrides) ─────────────────────────────────────

export type PendingChangeType =
  | "add_alias"
  | "override_validation_status"
  | "override_product_type"
  | "override_confidence";

export interface PendingChange {
  type: PendingChangeType;
  canonicalProductId: string;
  approved: boolean;
  approvedBy?: string;
  approvedAt?: string;
  alias?: string;
  validationStatus?: ValidationStatus;
  productType?: ProductType;
  confidence?: Confidence;
}

export interface PendingChangesFile {
  version: number;
  description: string;
  lastUpdatedAt: string | null;
  changes: PendingChange[];
}
